export const categories = [
  "Air Refresher",
  "Body Splashes",
  "Body Spray",
  "Cosmetics",
  "Designer Perfumes",
  "Diffusers",
  "Fragrance World",
  "Mini Perfumes",
  "Oil Perfumes",
  "Perfume Gift Sets",
  "Perfume Combos",
  "Smart Collections",
  "Afnan",
  "Armaf",
  "Dove Sure",
  "Efolia",
  "French Avenue",
  "Frank Oliver",
  "Khadlaj",
  "Lattafa",
  "L'affair",
  "Maison Alhambra",
  "Marque Collections",
  "Paris Corner",
  "Rayhaan",
  "Rassasi",
  "Riffs",
  "Other",
  "Clone",
  "Perfumes",
  "Colorful Bomb",
  "Ikeda Air Freshener - 120ml",
  "Ikeda Air Freshener- 60ml",
  "Nectar Initial",
  "Loris Diffuser 240ml",
  "Loris Diffuser 150ml",
  "Loris Diffuser 120ml",
  "Loris Diffuser 100ml",
  "Loris Car Spray",
  "Loris Room Spray",
  "Mens Combos",
  "Ladies Combos",
  "Unisex Combos",
  "Monogotas Splash",
  "Bath & Body Works Splash",
  "Brazilian Crush",
  "EOS Cream",
  "Men Splashes",
  "Atomizers",
];
